### ISSUE TITLE
request is deprecated for a year. 

### ISSUE THREAD

**Issue by oliverjessner** [tumblr/tumblr.js#103] opened 2021-01-27 12:46 UTC
Is there any chance that the tumblr team is migrating to something more up to date, like https://www.npmjs.com/package/node-fetch?

**Comment by sirreal** [comment] 2023-07-21 13:10
This is a priority issue we're working on.

**Comment by sirreal** [comment] 2023-07-21 14:18
This is a duplicate of #91

**Closed by sirreal** 2023-07-21 14:18 UTC
