### ISSUE TITLE
Documentation very unclear on photo data format

### ISSUE THREAD

**Issue by unwitting** [tumblr/tumblr.js#38] opened 2015-07-17 20:18 UTC
The documentation points you at the Tumblr API docs eg https://www.tumblr.com/docs/en/api/v2#posting for options information, however for photo posting this is pretty inaccurate. For photo posts the API docs say:

>Array (URL-encoded binary contents)

as the format for photo `data`. Base-64, URL-encoded seems to be what you want. A user of this JS API could easily (and at least one has :P) spend a lot of time trying to work out why their lovingly crafted image data isn't uploading, when in fact all they needed to give was the local filename and have it handled for them.

**Comment by KevinTCoughlin** [comment] 2015-07-21 03:50
Yea, the README is unclear without looking at the [source](https://github.com/tumblr/tumblr.js/blob/master/lib/tumblr.js#L205) that photo post creation expects a file path for `data`. I'll probably address that in a quick PR unless we agree that the official API docs need clarification as well.

cc: @ngreenwood6 @ceykooo

**Comment by unwitting** [comment] 2015-08-08 14:03
Bump?

**Comment by unwitting** [comment] 2016-04-13 17:12
Again @ngreenwood6 @ceyko

**Comment by kmck** [comment] 2016-06-07 22:50
Closing this as kind of a duplicate of https://github.com/tumblr/tumblr.js/issues/38

Still a known issue on our side that the photo upload API is a little inconsistent.

**Closed by kmck** 2016-06-07 22:50 UTC
