### ISSUE TITLE
Unable to Change Ask Post Privacy

### ISSUE THREAD

**Issue by foreveranon** [tumblr/tumblr.js#90] opened 2019-11-23 19:49 UTC
I'm running a script to turn a number of posts on a Tumblr private in bulk, using this API. I'm seeing two issues:

1. For some reason, it doesn't work on ask posts... I keep getting back 400 errors when I try to make an ask post private
2. Code that was working fine before is suddenly throwing back a 400 error for almost all posts I try to update, for no clear reason.

The code I'm using to make the posts private is:

```
function makePrivate(client, user, offset) {
    return client.blogPosts(user, {
        offset: offset,
        limit: 20
    }).then((resp) => {
            var newPosts = resp && resp.posts ? resp.posts : [];
            var toUpdate = [];
            if (newPosts.length > 0) {
                newPosts.forEach(post => {
                    if(post.state === 'published') {
                        toUpdate.push(post);
                    }
                })
            }
            let postsPromise = toUpdate.map(updatePost.bind(this, client, user, 0));
            return Promise.all(postsPromise);
        }).then((results) => {
            fs.writeFileSync('error-posts.json', JSON.stringify(errorPosts));
            offset += 20;
            return postRecursor(client, user, offset);
        });
}

function updatePost(client, user, retries, post) {
    retries = retries || 0;
    return new Promise((resolve, reject) => {
        return client.editPost(user, {
            id: post.id,
            state: 'private'
        }).then(resolve).catch(error => {
            console.error('Error updating post', error);
            let errorString = (error && error.message ? error.message : String(error);
            if(retries < 5 && errorString.includes('429 Limit Exceeded')) {
                setTimeout(() => {
                    updatePost(client, user, retries + 1, post)
                }, 5400000);
            }
            else {
                return reject(error);
            }
        });
    });
}
```

**Comment by foreveranon** [comment] 2019-11-29 22:14
As an update: for whatever reason, the issue with all posts giving me 400 errors went away when I closed and reopened Firefox. However, I am still unable to update ask posts in this fashion.

**Comment by foreveranon** [comment] 2019-12-05 12:53
Is there somewhere else I could go to get support for this? I put in a membership request for the Google Group, but it's been a while now and my membership request is still pending, plus no activity on either of the open tickets on this project...

**Comment by oliverjessner** [comment] 2019-12-05 15:29
@foreveranon the tumblr group is pretty much dead and tumblr  is not investing a lot of work power into the SDK Same goes for the old https://developers.tumblr.com/tagged/changelog dev blog. 
As far as I can remember the same issue occurs on queued posts.

Not sure about the future of the API anyway, I wish we could get at least some updates, a regular updated markdown file/a twitter acc would be enough. Also when is the NPF done? I wish tumblr could give some feedback. #NoHateJustLoveForTumblr

**Comment by cyle** [comment] 2019-12-05 16:02
> Not sure about the future of the API anyway, I wish we could get at least some updates, a regular updated markdown file/a twitter acc would be enough. Also when is the NPF done? I wish tumblr could give some feedback. #NoHateJustLoveForTumblr

Hello! The Tumblr public API docs and documentation about NPF are here: https://github.com/tumblr/docs I'm sorry we didn't communicate that clearly enough across all of our open source repos, like this one. The [official Tumblr Engineering blog](https://engineering.tumblr.com/) is the best place to follow for updates from us.

@foreveranon -- could you perform this same change to a post in Tumblr itself? As in, go to Tumblr.com, log in, and change an ask/answer post to private without this same error? Do you have an example post you can provide? Thanks!

**Comment by foreveranon** [comment] 2019-12-05 17:20
I can, yes. Ghat was the first thing I tested when I foud this issue. Possibly noteworthy: when I edit a published ask post to change its privacy, Tumblr seems to think its posting date changed, and it jumps to the 'top' of my post list when I look at my posts, even if it's years old. I'm not comfortable sharing any of the posts I'm getting this issue with (since the whole issue here is that I'm trying to make them private in bulk), but to replicate, ask a question to a blog and publish it, then try to edit the post via Tumblr.js. If that doesn't work then I'll make some dummy blogs when I get home and see if I can set up an example for you.

Thanks!

**Comment by cyle** [comment] 2019-12-05 17:29
Thanks, I'm just trying to isolate whether this is an issue with the logic on Tumblr itself or within this library. Since I can send one of my test blogs an ask, answer it (and publish it), and then edit that post to be private either on web or in one of the Tumblr mobile apps, I feel like the problem is somewhere in this library. Just making sure before proceeding further!

**Comment by foreveranon** [comment] 2019-12-05 17:48
Gotcha. Thanks again! For what worth, I haven't tried this with any of the packages for other languages, so the problem could be in either the underlying API or in the package itself.

Thanks again!

**Comment by cyle** [comment] 2019-12-06 16:13
This did turn out to be a bug on Tumblr's side after further investigation, and it should be fixed now. Can you try again and see if it's working for you?

**Comment by foreveranon** [comment] 2019-12-10 23:22
That seems to have resolved it! Thank you! You may close this as internal tracking needs dictate.

**Comment by cyle** [comment] 2019-12-10 23:31
👌

**Comment by sirreal** [comment] 2023-07-21 14:19
It looks like this is resolved.

**Closed by sirreal** 2023-07-21 14:19 UTC
